In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import  train_test_split


In [ ]:
data=pd.read_csv("/content/Salary_Data.csv")

In [ ]:
data.shape

(30, 2)

In [ ]:
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [ ]:
X=data[['YearsExperience']]

In [ ]:
y=data[['Salary']]

In [ ]:
X_train,X_Test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=100)

In [ ]:
print(X_train.shape)
print(X_Test.shape)
print(y_train.shape)
print(y_test.shape)

(24, 1)
(6, 1)
(24, 1)
(6, 1)


In [ ]:
X_train.head

<bound method NDFrame.head of     YearsExperience
27              9.6
25              9.0
6               3.0
17              5.3
22              7.9
11              4.0
4               2.2
29             10.5
0               1.1
1               1.3
18              5.9
14              4.5
19              6.0
21              7.1
2               1.5
20              6.8
10              3.9
16              5.1
15              4.9
23              8.2
7               3.2
3               2.0
24              8.7
8               3.2>

In [ ]:
X_Test.head

<bound method NDFrame.head of     YearsExperience
9               3.7
26              9.5
28             10.3
13              4.1
5               2.9
12              4.0>

In [ ]:
y_train.head

<bound method NDFrame.head of       Salary
27  112635.0
25  105582.0
6    60150.0
17   83088.0
22  101302.0
11   55794.0
4    39891.0
29  121872.0
0    39343.0
1    46205.0
18   81363.0
14   61111.0
19   93940.0
21   98273.0
2    37731.0
20   91738.0
10   63218.0
16   66029.0
15   67938.0
23  113812.0
7    54445.0
3    43525.0
24  109431.0
8    64445.0>

In [ ]:
y_test.head

<bound method NDFrame.head of       Salary
9    57189.0
26  116969.0
28  122391.0
13   57081.0
5    56642.0
12   56957.0>

In [ ]:
data.head(15)

YearsExperience   Salary
0               1.1  39343.0
1               1.3  46205.0
2               1.5  37731.0
3               2.0  43525.0
4               2.2  39891.0
5               2.9  56642.0
6               3.0  60150.0
7               3.2  54445.0
8               3.2  64445.0
9               3.7  57189.0
10              3.9  63218.0
11              4.0  55794.0
12              4.0  56957.0
13              4.1  57081.0
14              4.5  61111.0

In [ ]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
lm.coef_

array([[9361.11639032]])

In [ ]:
lm.intercept_

array([26819.0651187])

In [ ]:
# y=mx+c, m=coeff_, c=intercept_


In [ ]:
#Sal=9361*exp+26819
#Sal=9361*6+26819

In [ ]:
y_pred=lm.predict(X_Test)

In [ ]:
y_pred

array([[ 61455.19576289],
       [115749.67082676],
       [123238.56393901],
       [ 65199.64231902],
       [ 53966.30265063],
       [ 64263.53067999]])

In [ ]:
# comparing the result
y_test.head

<bound method NDFrame.head of       Salary
9    57189.0
26  116969.0
28  122391.0
13   57081.0
5    56642.0
12   56957.0>

In [ ]:
error=y_test-y_pred


In [ ]:
error

Salary
9  -4266.195763
26  1219.329173
28  -847.563939
13 -8118.642319
5   2675.697349
12 -7306.530680

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score
from math import  sqrt
mse=mean_squared_error(y_test,y_pred)

In [ ]:
mse

24477109.08965574

In [ ]:
r2_score(y_test,y_pred)

0.9720725422361338

In [ ]:
rmse=sqrt(mse)
print(rmse)

4947.434596804261
